"""
HTML export — generate standalone animated HTML from PLogoSchema.

The geometry (nodes, edges, arcs, nib) is serialized to JSON and
injected into an HTML template containing all Three.js rendering logic.
"""

from __future__ import annotations

import json
from pathlib import Path
from p_logo.types import PLogoSchema
from p_logo.exporters.node_colors import (
    resolve_node_color, ARC_STYLES, compute_degrees, node_core_radius,
)


# ── Schema → JS data ─────────────────────────────────────────

def schema_to_js_data(schema: PLogoSchema) -> dict:
    """
    Convert PLogoSchema to a JSON-serializable dict for HTML injection.

    Returns dict with keys: wireNodes, wireEdges, arcDefs, nib.
    Color assignments use string keys (resolved to THREE.Color in the template).
    """

    # Nodes (canonical degree-based sizing)
    degrees = compute_degrees(schema)
    wire_nodes = []
    for node in schema.nodes:
        col = resolve_node_color(node)
        wire_nodes.append({
            "x": node.x,
            "y": node.y,
            "col": col,
        })

    # Edges
    wire_edges = [[e.from_id, e.to_id] for e in schema.edges]

    # Arcs
    arc_defs = []
    for i, arc in enumerate(schema.arcs):
        style = ARC_STYLES[i]
        arc_defs.append({
            "cx": arc.cx,
            "cy": arc.cy,
            "r": arc.radius,
            "startAngle": arc.start_angle,
            "sweep": arc.sweep_angle,
            "color": style["color"],
            "opacity": style["opacity"],
        })

    # Nib
    nib = schema.nib
    waist_y = nib.outline[1][1]  # right shoulder y = Circ.Rect.I top
    nib_data = {
        "tipY": nib.outline[0][1],
        "topY": waist_y,
        "cx": nib.ball_pos[0],
        "left": nib.outline[3][0],   # left shoulder x
        "right": nib.outline[1][0],  # right shoulder x
        "ctrY": nib.ball_pos[1],
        "outline": [list(p) for p in nib.outline],
        "slitStart": list(nib.slit_start),
        "slitEnd": list(nib.slit_end),
        "ballPos": list(nib.ball_pos),
    }

    return {
        "wireNodes": wire_nodes,
        "wireEdges": wire_edges,
        "arcDefs": arc_defs,
        "nib": nib_data,
    }


def export_html(
    schema: PLogoSchema,
    output_path: str,
    template: str = "animated_revision",
    style: dict | None = None,
) -> str:
    """
    Generate a standalone animated HTML file from schema + template.

    Args:
        schema: The PLogoSchema to inject
        output_path: Where to write the HTML
        template: Template name (looks in templates/ directory)
        style: Optional style overrides (reserved for future use)

    Returns:
        The generated HTML string
    """
    templates_dir = Path(__file__).parent / "templates"
    template_path = templates_dir / f"{template}.html"

    if not template_path.exists():
        raise FileNotFoundError(f"Template not found: {template_path}")

    template_html = template_path.read_text(encoding="utf-8")
    data = schema_to_js_data(schema)

    # Inject JSON into placeholders
    replacements = {
        "/* __WIRE_NODES__ */[]": json.dumps(data["wireNodes"], indent=4),
        "/* __WIRE_EDGES__ */[]": json.dumps(data["wireEdges"]),
        "/* __ARC_DEFS__ */[]": json.dumps(data["arcDefs"], indent=4),
        "/* __NIB_DATA__ */{}": json.dumps(data["nib"], indent=4),
    }

    html = template_html
    for placeholder, replacement in replacements.items():
        html = html.replace(placeholder, replacement)

    # Add generation header after <!DOCTYPE html>
    header = (
        f"<!-- GENERATED by p_logo/exporters/html_export.py — DO NOT EDIT geometry sections.\n"
        f"     Schema: {schema.node_count} nodes, {schema.edge_count} edges, {len(schema.arcs)} arcs.\n"
        f"     Regenerate: from p_logo import build_schema; "
        f"from p_logo.exporters.html_export import export_html; "
        f"export_html(build_schema(), '{Path(output_path).name}') -->\n"
    )
    html = html.replace("<!DOCTYPE html>\n", f"<!DOCTYPE html>\n{header}", 1)

    Path(output_path).write_text(html, encoding="utf-8")
    return html
