"""
Phase 0 — JSON export compatibility tests.

The library's export_json must produce output identical to the existing
p_logo_schema.json (which was generated by the old geometric_p_logo.py).

These tests must pass BEFORE any script migration begins.
"""

import json
import sys
import pytest
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))


@pytest.fixture(scope="module")
def old_schema():
    with open(ROOT / "build" / "p_logo_schema.json") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def new_schema():
    from p_logo import build_schema
    from p_logo.exporters.json_export import schema_to_dict
    return schema_to_dict(build_schema())


class TestJsonExportCompat:
    def test_rect1_vertex_keys_use_p_rect_prefix(self, new_schema):
        """Rect.1 vertices must use P.RECT.UL/UR/LL/LR keys, not upper_left etc."""
        keys = set(new_schema["geometry"]["shapes"]["Rect.1"]["vertices"].keys())
        assert keys == {"P.RECT.UL", "P.RECT.UR", "P.RECT.LL", "P.RECT.LR"}

    def test_edge_format_no_type_field(self, new_schema):
        """Each edge dict must have only 'from' and 'to' keys (no 'type')."""
        for e in new_schema["graph"]["edges"]:
            assert set(e.keys()) == {"from", "to"}, f"Unexpected keys in edge: {e}"

    def test_node_count_matches(self, old_schema, new_schema):
        assert len(new_schema["graph"]["nodes"]) == len(old_schema["graph"]["nodes"])

    def test_edge_count_matches(self, old_schema, new_schema):
        assert len(new_schema["graph"]["edges"]) == len(old_schema["graph"]["edges"])

    def test_node_positions_match(self, old_schema, new_schema):
        for o, n in zip(old_schema["graph"]["nodes"], new_schema["graph"]["nodes"]):
            assert o["x"] == pytest.approx(n["x"], abs=0.002), f"Node {o['id']} x mismatch"
            assert o["y"] == pytest.approx(n["y"], abs=0.002), f"Node {o['id']} y mismatch"

    def test_edge_set_matches(self, old_schema, new_schema):
        old_edges = set((e["from"], e["to"]) for e in old_schema["graph"]["edges"])
        new_edges = set((e["from"], e["to"]) for e in new_schema["graph"]["edges"])
        assert old_edges == new_edges

    def test_arc_radii_match(self, old_schema, new_schema):
        for o, n in zip(old_schema["geometry"]["arcs"], new_schema["geometry"]["arcs"]):
            assert o["radius"] == pytest.approx(n["radius"], abs=1e-3)

    def test_derived_radii_match(self, old_schema, new_schema):
        for key in ["Circ.D", "Circ.Bounds.A", "Circ.A"]:
            ov = old_schema["coordinate_system"]["derived_radii"][key]["value"]
            nv = new_schema["coordinate_system"]["derived_radii"][key]["value"]
            assert ov == pytest.approx(nv, abs=1e-4), f"{key} mismatch"

    def test_rect1_dimensions_match(self, old_schema, new_schema):
        old_r = old_schema["geometry"]["shapes"]["Rect.1"]
        new_r = new_schema["geometry"]["shapes"]["Rect.1"]
        assert old_r["width"] == pytest.approx(new_r["width"], abs=1e-3)
        assert old_r["height"] == pytest.approx(new_r["height"], abs=1e-3)

    def test_rect1_vertex_values_match(self, old_schema, new_schema):
        """Values must match regardless of key naming."""
        old_v = old_schema["geometry"]["shapes"]["Rect.1"]["vertices"]
        new_v = new_schema["geometry"]["shapes"]["Rect.1"]["vertices"]
        # Map old keys to new keys
        mapping = {"P.RECT.UL": "P.RECT.UL", "P.RECT.UR": "P.RECT.UR",
                   "P.RECT.LL": "P.RECT.LL", "P.RECT.LR": "P.RECT.LR"}
        for ok, nk in mapping.items():
            assert old_v[ok]["x"] == pytest.approx(new_v[nk]["x"], abs=0.002)
            assert old_v[ok]["y"] == pytest.approx(new_v[nk]["y"], abs=0.002)
